services:
  mysqldb:
    image: mysql:8.0
    container_name: mysqlcontainer
    command: --default-authentication-plugin=mysql_native_password
    restart: unless-stopped
    volumes:
      - ./dbinit/init.sql:/docker-entrypoint-initdb.d/0_init.sql
      - $HOME/database:/var/lib/mysql
    ports:
      - 3307:3307
    expose:
      - 3307
    environment:
      MYSQL_DATABASE: qp_db
      MYSQL_USER: admin
      MYSQL_PASSWORD: letmein
      MYSQL_ROOT_PASSWORD: letmein
      SERVICE_TAGS: dev
      SERVICE_NAME: mysqldb
    networks:
      - internalnet

  nodeapp:
    container_name: nodeappcontainer
    build: .
    image: nodeapp:v1
    environment:
      DB_HOST: mysqldb
      DB_USER: 'root'
      DB_PASSWORD: 'letmein'
      DB_NAME: patients
      DB_PORT: 3307
      DB_CONNECTION_LIMIT: 10
      SERVER_PORT: 8081
    ports:
      - 8081:8081
    expose:
      - 8081
    depends_on:
      - mysqldb
    networks:
      - internalnet

networks:
  internalnet:
    driver: bridge